/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: ef23a8e1356f032eb42120df3a581f0d)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
	AI_MODEL: "@cf/meta/llama-3.1-8b-instruct-fast";
	ALLOW_DEBUG_VIP: "true";
	SMS_REGISTRATION_LIMIT: "100";
	SMS_FALLBACK_THRESHOLD: "10";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
